image: docker:latest
services:
  - docker:dind

variables:
  #DOCKER_DRIVER: overlay
  APP_NAME: bingo
  APP_VERSION: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  APP_NAMESPACE: app-bingo
  #APP INFO
  IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
  IMAGE_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:latest
  IMAGE_PHP: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG-php:latest
  IMAGE_WS: $CI_REGISTRY_IMAGE/ws-$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
  IMAGE_WEB: $CI_REGISTRY_IMAGE/web-$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA

 
stages:
  - pre-build
  - test
  - build
  - publish

pre-build-job:
  stage: pre-build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  tags:
    - k3s-ho
  only:
    changes:
      - docker/php/Dockerfile

  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/docker/php/Dockerfile"
      --destination "$IMAGE_PHP"
      --destination "$IMAGE_LATEST"


pre-build-job-ws:
  stage: pre-build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  tags:
    - k3s-ho

  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/docker/php/Dockerfile-websocket"
      --destination "$IMAGE_WS"

pre-build-job-web:
  stage: pre-build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  tags:
    - k3s-ho


  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/docker/php/Dockerfile-web"
      --destination "$IMAGE_WEB"


deploy-prod-ws-ho:
  stage: publish
  image: dtzar/helm-kubectl
  needs:
    - build-job
  only:
    - main
  when: manual
  environment:
    name: production
  tags:
    - k3s-ho
  script:
    - helm upgrade --install $APP_NAME helm/websocket --set image.tag=$CI_COMMIT_SHA --set APP_VERSION=$APP_VERSION --set APP_DATE=$CI_PIPELINE_CREATED_AT  --set MONGO_DSN=$MONGO_DSN  --namespace=$APP_NAMESPACE -f helm/websocket/values.yaml
